"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var subModule_1 = require("subModule");
var kotlin = require("kotlinModule");
var scala = require("scalaModule");
console.log(scala);
console.log(scala.calc(900));
console.log(kotlin);
console.log(kotlin.doubling(200));
console.log(subModule_1.default(100));
